// Auto-generated by update-version.ps1 - DO NOT EDIT MANUALLY
// Build timestamp: 2026-04-26 16:27:19
// Build configuration: Release

namespace DirectAbandonSet
{
    public static class BuildVersion
    {
        public const string Version = "0.002(R)";
        public const string VersionNumber = "0.002";
        public const string BuildType = "R";
        public const string BuildConfig = "Release";
        public const string BuildTimestamp = "2026-04-26 16:27:19";
    }
}
